// GraphQL Mutations - Generated by Amplify CLI
// RUN: amplify codegen to generate this file

// Placeholder - will be replaced by amplify codegen
export const createUser = ``;
export const updateUser = ``;
export const deleteUser = ``;
export const createConversation = ``;
export const updateConversation = ``;
export const deleteConversation = ``;
export const createMessage = ``;
export const updateMessage = ``;
export const deleteMessage = ``;
export const createConversationParticipant = ``;
export const updateConversationParticipant = ``;
export const deleteConversationParticipant = ``;

