// GraphQL Queries - Generated by Amplify CLI
// RUN: amplify codegen to generate this file

// Placeholder - will be replaced by amplify codegen
export const getUser = ``;
export const getUserByEmail = ``;
export const getUserByUsername = ``;
export const listUsers = ``;
export const getConversation = ``;
export const listConversations = ``;
export const getMessage = ``;
export const listMessages = ``;
export const messagesByConversationIdAndCreatedAt = ``;
export const messagesBySenderIdAndCreatedAt = ``;
export const conversationParticipantsByUserIdAndConversationId = ``;
export const conversationParticipantsByConversationIdAndUserId = ``;

