// GraphQL Subscriptions - Generated by Amplify CLI
// RUN: amplify codegen to generate this file

// Placeholder - will be replaced by amplify codegen
export const onCreateMessage = ``;
export const onUpdateMessage = ``;
export const onDeleteMessage = ``;
export const onCreateConversation = ``;
export const onUpdateConversation = ``;
export const onDeleteConversation = ``;

